version: "3.8"

services:
  # NestJS Mock-IT backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      # Build development stage from dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    # dev mode
    command: sh -c "sleep 15 && npx prisma migrate deploy && npm run start:docker"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    ports:
      - "20000:20000"
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "22000:5432"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    command: npm run start
    volumes:
      - ./frontend:/frontend/src/app
      - /frontend/src/app/node_modules
    ports:
      - "21000:21000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
